version: '3.8'

services:
  app:
    build: .
    container_name: pdf_web_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: pdfstore
      DB_USER: user
      DB_PASS: pass

  db:
    image: postgres:15
    container_name: pdf_postgres
    environment:
      POSTGRES_DB: pdfstore
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: